- name: Configure webserver with nginx
  hosts: localhost
  gather_facts: true
  become: True

  tasks:
    - name: Install nginx
      package: name=nginx update_cache=yes

    - name: Copy nginx config file
      copy:
        src: files/nginx.conf
        dest: /etc/nginx/sites-available/default

    - name: Enable configuration
      file:
        dest: /etc/nginx/sites-enabled/default
        src: /etc/nginx/sites-available/default
        state: link

    - name: Copy index.html
      template:
        src: templates/index.html.j2
        dest: /usr/share/nginx/html/index.html

    - name: Get Nginx service status
      systemd:
        name: nginx
        state: started
        enabled: yes
      register: result

    - name: Display Nginx service status
      debug:
        msg: "{{result}}"

    - name: Gathering service facts
      service_facts:

    - name: Get facts
      debug:
        msg: "{{ ansible_facts.services['nginx'].status }}"
    
    - name: Restart nginx
      service:
        name: nginx
        state: restarted
